![New York City schoolbus](schoolbus.jpg)

Photo by [Jannis Lucas](https://unsplash.com/@jannis_lucas) on [Unsplash](https://unsplash.com).
<br>

Every year, American high school students take SATs, which are standardized tests intended to measure literacy, numeracy, and writing skills. There are three sections - reading, math, and writing, each with a **maximum score of 800 points**. These tests are extremely important for students and colleges, as they play a pivotal role in the admissions process.

Analyzing the performance of schools is important for a variety of stakeholders, including policy and education professionals, researchers, government, and even parents considering which school their children should attend. 

You have been provided with a dataset called `schools.csv`, which is previewed below.

You have been tasked with answering three key questions about New York City (NYC) public school SAT performance.

In [1]:
# Re-run this cell 
import pandas as pd

# Read in the data
schools = pd.read_csv("schools.csv")

# Preview the data
print(schools.head())

#best schools for math
best_math_schools = schools[schools['average_math'] > (80/100)*800][['school_name','average_math']].sort_values('average_math',ascending=False)
print(best_math_schools)

#average SAT result
schools['total_SAT'] = schools['average_math']+schools['average_reading']+schools['average_writing']

#top 10 performing schools
top_10_schools = schools.sort_values('total_SAT',ascending=False)[['school_name','total_SAT']].head(10)
print(top_10_schools)

#NYC borough with highest standard deviation for total_SAT
boroughs = schools.groupby('borough')['total_SAT'].agg(['count','mean','std']).round(2)

#filter for max std and making borough a column
largest_std_dev = boroughs[boroughs["std"] == boroughs["std"].max()]

#Renaming the columns
largest_std_dev = largest_std_dev.rename(columns={'count':'num_schools','mean':'average_SAT','std':'std_SAT'})

# Moving borough as column than as index
largest_std_dev.reset_index(inplace=True)
print(largest_std_dev)

                                         school_name  ... percent_tested
0  New Explorations into Science, Technology and ...  ...            NaN
1                               Essex Street Academy  ...           78.9
2                       Lower Manhattan Arts Academy  ...           65.1
3    High School for Dual Language and Asian Studies  ...           95.9
4      Henry Street School for International Studies  ...           59.7

[5 rows x 7 columns]
                                           school_name  average_math
88                              Stuyvesant High School           754
170                       Bronx High School of Science           714
93                 Staten Island Technical High School           711
365  Queens High School for the Sciences at York Co...           701
68   High School for Mathematics, Science, and Engi...           683
280                     Brooklyn Technical High School           682
333                        Townsend Harris High School           680
174  High School of American Studies at Lehman College           669
0    New Explorations into Science, Technology and ...           657
45                       Eleanor Roosevelt High School           641
                                           school_name  total_SAT
88                              Stuyvesant High School       2144
170                       Bronx High School of Science       2041
93                 Staten Island Technical High School       2041
174  High School of American Studies at Lehman College       2013
333                        Townsend Harris High School       1981
365  Queens High School for the Sciences at York Co...       1947
5                       Bard High School Early College       1914
280                     Brooklyn Technical High School       1896
45                       Eleanor Roosevelt High School       1889
68   High School for Mathematics, Science, and Engi...       1889
     borough  num_schools  average_SAT  std_SAT
0  Manhattan           89      1340.13   230.29